<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../HareQueue.Build.props" />

  <ItemGroup>
    <ProjectReference Include="..\HareQueue.RabbitMq.Abstractions\HareQueue.RabbitMq.Abstractions.csproj" />
    <ProjectReference Include="..\HareQueue.RabbitMq.Serializer\HareQueue.RabbitMq.Serializer.csproj" />
  </ItemGroup>

</Project>
